-- ============================================================
-- MODELO RELACIONAL - PROYECTO SQL


-- Este archivo contiene la estructura relacional (tablas,
-- claves primarias, foráneas, restricciones y tipos de datos).
-- No contiene INSERT, secuencias, triggers ni vistas.
-- ============================================================

CREATE TABLE ROL (
    ID_ROL NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_ROL_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE PERMISO (
    ID_PERMISO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(80) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_PERMISO_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE ROL_PERMISO (
    ID_ROL NUMBER NOT NULL,
    ID_PERMISO NUMBER NOT NULL,
    CONSTRAINT PK_ROL_PERMISO PRIMARY KEY (ID_ROL, ID_PERMISO),
    CONSTRAINT FK_RP_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    CONSTRAINT FK_RP_PERMISO FOREIGN KEY (ID_PERMISO) REFERENCES PERMISO(ID_PERMISO)
);

CREATE TABLE CURSO (
    ID_CURSO NUMBER PRIMARY KEY,
    NIVEL VARCHAR2(20) NOT NULL,
    LETRA VARCHAR2(5) NOT NULL,
    ANIO NUMBER(4) NOT NULL,
    ESPECIALIDAD VARCHAR2(100),
    PROFESOR_JEFE VARCHAR2(150),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO',
    CONSTRAINT CK_CURSO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE ALUMNO (
    ID_ALUMNO NUMBER PRIMARY KEY,
    RUT VARCHAR2(12) NOT NULL,
    DV CHAR(1) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(50) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(50),
    FECHA_NACIMIENTO DATE,
    CORREO VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    ID_CURSO NUMBER,
    ESPECIALIDAD VARCHAR2(100),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO',
    CONSTRAINT UK_ALUMNO_RUT UNIQUE (RUT),
    CONSTRAINT FK_ALUMNO_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
    CONSTRAINT CK_ALUMNO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO','EGRESADO'))
);

CREATE TABLE PROFESOR (
    ID_PROFESOR NUMBER PRIMARY KEY,
    RUT VARCHAR2(12) NOT NULL,
    DV CHAR(1) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(50) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(50),
    CORREO VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    ESPECIALIDAD VARCHAR2(100),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO',
    CONSTRAINT UK_PROFESOR_RUT UNIQUE (RUT),
    CONSTRAINT CK_PROFESOR_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE ESPACIO (
    ID_ESPACIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50),
    UBICACION VARCHAR2(150),
    RESPONSABLE VARCHAR2(150),
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO',
    CONSTRAINT UK_ESPACIO_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CK_ESPACIO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE CATEGORIA_INVENTARIO (
    ID_CATEGORIA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(250),
    CONSTRAINT UK_CATEGORIA_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE MARCA (
    ID_MARCA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(80) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_MARCA_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE ESTADO_EQUIPO (
    ID_ESTADO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    CONSTRAINT UK_ESTADO_EQUIPO_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE INVENTARIO (
    ID_INVENTARIO NUMBER PRIMARY KEY,
    CODIGO_INVENTARIO VARCHAR2(30) NOT NULL,
    NOMBRE VARCHAR2(150) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    ID_CATEGORIA NUMBER NOT NULL,
    ID_MARCA NUMBER,
    MODELO VARCHAR2(100),
    NUMERO_SERIE VARCHAR2(100),
    CANTIDAD NUMBER DEFAULT 1 NOT NULL,
    FECHA_ADQUISICION DATE,
    VALOR NUMBER(12,2),
    ID_ESTADO NUMBER NOT NULL,
    ID_ESPACIO NUMBER,
    OBSERVACION VARCHAR2(500),
    CONSTRAINT UK_INVENTARIO_CODIGO UNIQUE (CODIGO_INVENTARIO),
    CONSTRAINT UK_INVENTARIO_SERIE UNIQUE (NUMERO_SERIE),
    CONSTRAINT FK_INV_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_INVENTARIO(ID_CATEGORIA),
    CONSTRAINT FK_INV_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA),
    CONSTRAINT FK_INV_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_EQUIPO(ID_ESTADO),
    CONSTRAINT FK_INV_ESPACIO FOREIGN KEY (ID_ESPACIO) REFERENCES ESPACIO(ID_ESPACIO),
    CONSTRAINT CK_INVENTARIO_CANTIDAD CHECK (CANTIDAD >= 0),
    CONSTRAINT CK_INVENTARIO_VALOR CHECK (VALOR >= 0)
);

CREATE TABLE USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD_HASH VARCHAR2(200) NOT NULL,
    NOMBRE VARCHAR2(150) NOT NULL,
    CORREO VARCHAR2(100),
    ID_ROL NUMBER NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVO',
    FECHA_CREACION DATE DEFAULT SYSDATE,
    CONSTRAINT UK_USUARIO_USERNAME UNIQUE (USERNAME),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    CONSTRAINT CK_USUARIO_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
);

CREATE TABLE PRESTAMO (
    ID_PRESTAMO NUMBER PRIMARY KEY,
    FECHA_PRESTAMO DATE DEFAULT SYSDATE NOT NULL,
    FECHA_DEVOLUCION_PROGRAMADA DATE,
    FECHA_DEVOLUCION_REAL DATE,
    ID_ALUMNO NUMBER,
    ID_PROFESOR NUMBER,
    ESTADO VARCHAR2(30) DEFAULT 'PRESTADO',
    OBSERVACION VARCHAR2(500),
    CONSTRAINT FK_PRESTAMO_ALUMNO FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO),
    CONSTRAINT FK_PRESTAMO_PROFESOR FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR(ID_PROFESOR),
    CONSTRAINT CK_PRESTAMO_ESTADO CHECK (ESTADO IN ('PRESTADO','DEVUELTO','ATRASADO','PERDIDO','CANCELADO'))
);

CREATE TABLE DETALLE_PRESTAMO (
    ID_DETALLE NUMBER PRIMARY KEY,
    ID_PRESTAMO NUMBER NOT NULL,
    ID_INVENTARIO NUMBER NOT NULL,
    CANTIDAD NUMBER DEFAULT 1 NOT NULL,
    ESTADO_SALIDA VARCHAR2(50),
    ESTADO_DEVOLUCION VARCHAR2(50),
    OBSERVACION VARCHAR2(500),
    CONSTRAINT FK_DETALLE_PRESTAMO FOREIGN KEY (ID_PRESTAMO) REFERENCES PRESTAMO(ID_PRESTAMO),
    CONSTRAINT FK_DETALLE_INVENTARIO FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO(ID_INVENTARIO),
    CONSTRAINT CK_DETALLE_CANTIDAD CHECK (CANTIDAD > 0)
);

CREATE TABLE MANTENCION (
    ID_MANTENCION NUMBER PRIMARY KEY,
    ID_INVENTARIO NUMBER NOT NULL,
    FECHA_INGRESO DATE DEFAULT SYSDATE NOT NULL,
    FECHA_SALIDA DATE,
    TIPO_MANTENCION VARCHAR2(50),
    DESCRIPCION VARCHAR2(500),
    TECNICO_RESPONSABLE VARCHAR2(150),
    COSTO NUMBER(12,2) DEFAULT 0,
    ESTADO VARCHAR2(30) DEFAULT 'PENDIENTE',
    OBSERVACION VARCHAR2(500),
    CONSTRAINT FK_MANT_INVENTARIO FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO(ID_INVENTARIO),
    CONSTRAINT CK_MANT_ESTADO CHECK (ESTADO IN ('PENDIENTE','EN_PROCESO','FINALIZADA','CANCELADA')),
    CONSTRAINT CK_MANT_COSTO CHECK (COSTO >= 0)
);

CREATE TABLE MOVIMIENTO_INVENTARIO (
    ID_MOVIMIENTO NUMBER PRIMARY KEY,
    ID_INVENTARIO NUMBER NOT NULL,
    TIPO_MOVIMIENTO VARCHAR2(30) NOT NULL,
    FECHA_MOVIMIENTO DATE DEFAULT SYSDATE NOT NULL,
    CANTIDAD NUMBER DEFAULT 1 NOT NULL,
    ESPACIO_ORIGEN NUMBER,
    ESPACIO_DESTINO NUMBER,
    MOTIVO VARCHAR2(300),
    ID_USUARIO NUMBER,
    OBSERVACION VARCHAR2(500),
    CONSTRAINT FK_MOV_INVENTARIO FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO(ID_INVENTARIO),
    CONSTRAINT FK_MOV_ORIGEN FOREIGN KEY (ESPACIO_ORIGEN) REFERENCES ESPACIO(ID_ESPACIO),
    CONSTRAINT FK_MOV_DESTINO FOREIGN KEY (ESPACIO_DESTINO) REFERENCES ESPACIO(ID_ESPACIO),
    CONSTRAINT FK_MOV_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT CK_MOV_TIPO CHECK (TIPO_MOVIMIENTO IN ('INGRESO','SALIDA','TRASLADO','AJUSTE','PRESTAMO','DEVOLUCION','BAJA')),
    CONSTRAINT CK_MOV_CANTIDAD CHECK (CANTIDAD > 0)
);

CREATE TABLE AUDITORIA (
    ID_AUDITORIA NUMBER PRIMARY KEY,
    ID_USUARIO NUMBER,
    FECHA DATE DEFAULT SYSDATE,
    TABLA_AFECTADA VARCHAR2(100),
    OPERACION VARCHAR2(30),
    ID_REGISTRO NUMBER,
    DESCRIPCION VARCHAR2(500),
    CONSTRAINT FK_AUDITORIA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- ============================================================
-- FIN DEL MODELO RELACIONAL
-- ============================================================
